# Generated by Django 2.2.6 on 2019-10-31 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contest_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('contest_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Contest')),
                ('participant_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
