# Generated by Django 2.2.6 on 2019-10-31 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contest_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_participant',
            name='contest_name',
        ),
        migrations.RemoveField(
            model_name='contest_participant',
            name='participant_name',
        ),
        migrations.AddField(
            model_name='contest_participant',
            name='contest',
            field=models.ManyToManyField(to='core.Contest'),
        ),
        migrations.AddField(
            model_name='contest_participant',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
