# Generated by Django 2.2.6 on 2019-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191031_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_participant',
            name='status',
            field=models.CharField(choices=[('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('waiting', 'Đăng đợi')], default='waiting', max_length=32),
        ),
    ]
