# Generated by Django 2.2.6 on 2019-10-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contest_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_participant',
            name='status',
            field=models.CharField(choices=[('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('waiting', 'Đang đợi')], default='waiting', max_length=32),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=50)),
                ('phone_numer', models.CharField(max_length=20)),
                ('subject_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject')),
            ],
        ),
    ]
