# Generated by Django 2.2.6 on 2019-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191101_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_participant',
            name='subjects',
            field=models.ManyToManyField(to='core.Subject'),
        ),
    ]
