# Generated by Django 2.2.6 on 2019-11-01 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contest_participant_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_participant',
            name='contest',
        ),
        migrations.AddField(
            model_name='contest_participant',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contest'),
        ),
        migrations.RemoveField(
            model_name='contest_participant',
            name='participant',
        ),
        migrations.AddField(
            model_name='contest_participant',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
