# Generated by Django 2.2.6 on 2019-11-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject_test',
            new_name='identity_number',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
    ]
