# Generated by Django 2.2.6 on 2019-11-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191102_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('waiting', 'Đang đợi')], default='waiting', max_length=32)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contest')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
    ]
