# Generated by Django 2.2.6 on 2019-11-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('waiting', 'Đang đợi')], default='waiting', max_length=32),
        ),
        migrations.DeleteModel(
            name='Contest_Student',
        ),
    ]
